language: python
sudo: false
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install --use-mirrors pyyaml
  - pip install --use-mirrors -r requirements-dev.txt
script: nosetests
notifications:
  email: false
